name: Synchronize
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Update README
        env:
          ANILIST_TOKEN: ${{ secrets.ANILIST_TOKEN }}
        run: |-
          python favorites_updater.py
          python activity_updater.py
          cat README.md
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |-
          git pull
          git diff
          git config --global user.email "moe@chocola.dev"
          git config --global user.name "Moe Poi ~"
          git add -A
          git commit -m "Ara Ara ~" || exit 0
          git remote set-url --push origin https://moepoi:$GITHUB_TOKEN@github.com/moepoi/moepoi
          git push