name: Synchronize
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Commit and push if changed
        run: |-
          git pull
          git diff
          git config --global user.email "2859439384@qq.com"
          git config --global user.name "xiyueyezibile"
          git add -A
          git commit -m "Ara Ara ~" || exit 0
          git remote set-url --push origin https://github.com/xiyueyezibile/xiyueyezibile.git
          git push
